synthetic-package: false
arb-dir: lib/localization
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
preferred-supported-locales: [en]
# Fix localizations formatting
# https://github.com/flutter/flutter/issues/167982
# https://github.com/flutter/flutter/pull/167029
format: true
