name: dynamic_load
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0-115.0.dev <3.0.0'

dependencies:
  ffi: ^1.1.0
  win32: ^2.1.1

dev_dependencies:
  pedantic: ^1.10.0
  ffigen: ^4.0.0-dev.2
