name: Build Linux portable
on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - created
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev tree
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux

          mv build/linux/x64/release/bundle nyrna
          touch nyrna/PORTABLE
      - name: Add README
        run: |
          cat docs/_pages/usage.md >> README.md
          cp README.md nyrna/README.md
      - uses: actions/upload-artifact@v2
        with:
          name: nyrna-linux-portable
          path: nyrna/
