name: Publish MSIX to Microsoft Store

on:
  # Enable manual run
  workflow_dispatch:
  # Build & deploy for published releases
  release:
    types:
      - published

concurrency:
    group: ci-release-${{ github.ref }}-1
    cancel-in-progress: true

jobs:
    call-build-windows:
        uses: ./.github/workflows/build-windows.yml
        with:
          pre-release: false
        secrets: inherit

    docker:
        needs: call-build-windows
        runs-on: ubuntu-latest
        steps:
          - name: Download artifacts
            uses: actions/download-artifact@v3
            with:
              path: artifacts

          - name: Publish to Store
            uses: isaacrlevin/windows-store-action@main
            with:
                tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
                client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
                client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
                # "app-id" is the Store ID as listed in Partner Center
                # https://github.com/isaacrlevin/windows-store-action/issues/5#issuecomment-1086893615
                app-id: ${{ secrets.MICROSOFT_STORE_APP_ID }}
                package-path: "${{ github.workspace }}/artifacts/windows-store-artifact/"
                delete-pending: true
